###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Cook, CS165
# Author:
#     Jordan Jarvis
# Summary:
#     This program displays inventory information based on user input.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

