###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Cook, CS165
# Author:
#     Jordan Jarvis
# Summary:
#     This program uses multiple classes to keep track of user,
#     product, and shipping information.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

