###############################################################
# Program:
#     Week 10, Map
#     Brother Ercanbrack, CS235
# Author:
#     Jordan Jarvis
# Summary:
#     using Map to count words in text files
# Time:
#     9hrs
###############################################################

##############################################################
# The main rule
##############################################################
a.out: week10.o
	g++ -o a.out week10.o -std=c++11 -g
	tar -cf week10.tar *.cpp makefile

##############################################################
# The individual components
#      lesson10.o     : the driver program
##############################################################
week10.o: week10.cpp
	g++ -c week10.cpp -std=c++11 -g