###############################################################
# Program:
#     Check 05a, Getters and setters
#     Brother Cook, CS165
# Author:
#     Jordan Jarvis
# Summary:
#     This program gets and sets money values and displays them.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

